# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70525d616505da7de78be2e3b58f46e189559f1bc11132033aa5e5119db0700f321a639f2b35f404db8d175caf621bcf994c2a267985b10a50dfddf67d82927f

test:
  secret_key_base: 77ef4e82d509775650574e2083449ef371d4fa3bd4fbbe03b34ec13e2ad3c3056edf637b5d43fe565dbc39938236d9f74f8bff1366d637ff04a3b1994bd7b6fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
